### PR TITLE
Add request queue

### PR DESCRIPTION
**Pull request by hmwillson**
@binarydev 

This is a workaround for an issue where multiple near-simultaneous requests would bottleneck at the first call to Nightmare, leading the entire collection of requests to hang and then return in quick succession. I implemented the queue using the `async` library. All export requests are  enqueued and then only two are executed at a time.

### CODE REVIEW

**Comment by hmwillson** [comment]
@binarydev Thanks for figuring that out! I've made the change to use a `NUM_CORES` env variable to determine the number of concurrent requests to process from the queue.

**Comment by hmwillson** [comment]
@binarydev 

I've made three further changes, as discussed:

- Added a `waitTimeout` option that is passed to the Nightmare constructor
- Modified `findElementSizeAndDownload` to wait for the `selector` argument if present
- Added error handling to `findElementSizeAndDownload` to avoid unhandled promise rejections on wait timeout

To test, make a request with a custom `waitTimeout` and a `selector` that's not actually present on the page. Confirm that the timeout duration is observed and that you receive a response with status code 500 and an error message.

**Comment by binarydev** [comment]
@hmwillson The docker image fails to compile, because nvm doesn't have 8.10.17 to install. Either downgrade to 8.10.0, upgrade to 8.11, or find a way to make 8.10.17 work. I would suggest going with 8.10.0 since it's just a patch level difference.

**Comment by binarydev** [comment]
@hmwillson can you also update the readme with the new params, as well as a mention of the queue and env var? Thanks

**Comment by hmwillson** [comment]
@binarydev Dropped down to 8.10.0 and updated the README. Thanks for the quick review.

**Pull request merged**
